library(tidyverse)
library(readxl)

elo_sesso <- read_excel("D:/Personal Statistics/rcb/genere_elo_ir.xlsx") 
ir_open_gir <- read_excel("D:/Personal Statistics/rcb/ir_pt.xlsx", sheet = "open_ir") %>% filter(cat == "gir") %>% select(-cat)
ir_open_bra <- read_excel("D:/Personal Statistics/rcb/ir_pt.xlsx", sheet = "open_ir") %>% filter(cat == "bra") %>% select(-cat)
ir_femm_gir <- read_excel("D:/Personal Statistics/rcb/ir_pt.xlsx", sheet = "femminile_ir") %>% filter(cat == "gir") %>% select(-cat)
ir_femm_bra <- read_excel("D:/Personal Statistics/rcb/ir_pt.xlsx", sheet = "femminile_ir") %>% filter(cat == "bra") %>% select(-cat)
ir_mixed <- read_excel("D:/Personal Statistics/rcb/ir_pt.xlsx", sheet = "misto_ir") 
hot_mil_open <- read_excel("D:/Personal Statistics/rcb/hot_mil.xlsx", sheet = "open_mil") 
hot_mil_femm <- read_excel("D:/Personal Statistics/rcb/hot_mil.xlsx", sheet = "femminile") 
hot_mil_mix <- read_excel("D:/Personal Statistics/rcb/hot_mil.xlsx", sheet = "misto") 
nat_forli_pow <- read_excel("D:/Personal Statistics/rcb/Nationals.xlsx", sheet = "nomi_giusti") %>% filter(sit == "pow") %>% select(-sit)
nat_forli_ene <- read_excel("D:/Personal Statistics/rcb/Nationals.xlsx", sheet = "nomi_giusti") %>% filter(sit == "ene") %>% select(-sit)
nat_forli_bra <- read_excel("D:/Personal Statistics/rcb/Nationals.xlsx", sheet = "nomi_giusti") %>% filter(sit == "bra") %>% select(-sit)
nat_forli_mixed_pow <- read_excel("D:/Personal Statistics/rcb/Nationals.xlsx", sheet = "misto")%>% filter(sit == "pow") %>% select(-sit)
nat_forli_mixed_ene <- read_excel("D:/Personal Statistics/rcb/Nationals.xlsx", sheet = "misto")%>% filter(sit == "ene") %>% select(-sit)
nat_forli_mixed_bra <- read_excel("D:/Personal Statistics/rcb/Nationals.xlsx", sheet = "misto")%>% filter(sit == "bra") %>% select(-sit)
open_fw <-  read_excel("D:/Personal Statistics/rcb/ranking_winterspecial.xlsx", sheet = "nomi_giusti") %>% filter(cat == "Open") %>% select(-cat)
femm_xl <- read_excel("D:/Personal Statistics/rcb/femminile.xlsx", sheet = "nomi_giusti") %>% select(-P1,-P2)
mixed_fw <-  read_excel("D:/Personal Statistics/rcb/ranking_winterspecial.xlsx", sheet = "nomi_giusti") %>% filter(cat == "mixed") %>% select(-cat)
